### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by Foizman** [ljbc1994/BlazorIntersectionObserver#17]
**Hi there,**

great stuff, thank you!

Is there a delay as a parameter available, so that the IntersectionObserver triggers _context.IsIntersecting_ only after that delay in ms?

When there are 2 observed components on a page and we quickly scroll down to the lower one using jQuery/anchors, I found out that I get a NullReferenceError of the upper component, cause we intersect the upper component on scrolling for a split second on our way to the lower component.

Cheers,
FM

**Comment by ljbc1994** [comment]
Hey, 

Is that `NullReferenceError` coming from your code or this library? Just want to make sure if its a bug or a new feature that you're requesting?

Thanks!

**Comment by ljbc1994** [comment]
Hi Foizman,

It's been some time so I'm going to close this but please do raise an issue if you come back to this!

Thanks!
