### ISSUE TITLE
Give data to IntersectionObserve component and get it back in OnChange event

### ISSUE THREAD

**Issue by Michael-Anderlin** [ljbc1994/BlazorIntersectionObserver#20]
Hello,

I have a list of messages displayed as consecutive divs, each surrounded by a IntersectionObserve component.
I want to mark the message as read when becomes visible (API call).

How can I identify which message is concerned in the OnIntersectingChanged(IntersectionObserverEntry obj) event ?
How can I store the ID of the message in the IntersectionObserve Component

Won't it be possible to add something like a Data attribute that will be stored in the IntersectionObserve div and pass it back from Javascript to the IntersectionObserverEntry ?

Kind regards,

Michael

**Comment by ljbc1994** [comment]
Hi Michael,

I believe this is something that can be achieved by doing the following with components:

```razor
@foreach (var message in messages) {
      <IntersectionObserve Once=@true OnChange="() => OnMessageRead(message.Id)">
           <div class="message @(message.IsRead ? "message--read" : "message--unread")">
                 Message contents
           </div>
      </IntersectionObserve>
}

@functions {
      public IMessage[] Messages { get; set; }

      public void OnMessageRead(int messageId) {
         // call here
     }
}
```

Thanks

Louie

**Comment by Michael-Anderlin** [comment]
Cool, Tx for your help and you package !
