### ISSUE TITLE
Improved error checking and feedback

### ISSUE THREAD

**Issue by TLabWest** [ljbc1994/BlazorIntersectionObserver#32]
**Is your feature request related to a problem? Please describe.**
We had some trouble getting back on track after upgrading from a very early version to a later one. There are some important usage guidelines that ought to be more explicitly documented and and error checked.

**From the documentation:**
`<IntersectionObserve>
    <div @ref="context.Ref.Current">
        Hey... I'm @(context.IsIntersecting ? "in view": "out of view")
    </div>
</IntersectionObserve>`

While upgrading from an earlier version we noted the following issues:

- If the `<div>` element is missing (i.e. `<IntersectionObserve ... />`) the component will fail runtime with an obscure "Element doesn't implement interface" message or similar
- If the `<div>` element doesn't have the `@ref="context.Ref.Current"` markup it will fail runtime with a confusing null-ref exception
-  If the `<div>` element isn't rendered (i.e. `style=display:none`) the observer will not be triggered. This is different from earlier versions.

Although the documented exact usage works fine it would probably be a good idea to error check these caveats and give meaningful debugging feedback with relevant exceptions!

**Comment by ljbc1994** [comment]
Hey @TLabWest,

That's a great point, I'll look into putting nice error messages so it's a lot more helpful.
